#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  polos_keyboard_timestamp
#  
#  
import time
from pynput.keyboard import Key,Controller


def main(args):
    keyboard = Controller()
    time.sleep(4)
    keyboard.type('A')
    ts = time.time()
    time.sleep(1)
    keyboard.type(str(ts))
    
    return 0

if __name__ == '__main__':
    import sys
    sys.exit(main(sys.argv))
